services:
  postgres-users:
    image: 'postgres:latest'
    container_name: easybook-postgres-users
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  postgres-scheduling:
    image: 'postgres:latest'
    container_name: easybook-postgres-scheduling
    environment:
      - POSTGRES_DB=scheduling
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"